package com.tshepo.util;

public class EmailTemplates {
	
	
	public static String comfirmAccount(String name, String link) 
	{
		return "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
				+ "<head>\r\n"
				+ "<!--[if gte mso 9]>\r\n"
				+ "<xml>\r\n"
				+ "  <o:OfficeDocumentSettings>\r\n"
				+ "    <o:AllowPNG/>\r\n"
				+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
				+ "  </o:OfficeDocumentSettings>\r\n"
				+ "</xml>\r\n"
				+ "<![endif]-->\r\n"
				+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
				+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
				+ "  <title></title>\r\n"
				+ "  \r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "      @media only screen and (min-width: 620px) {\r\n"
				+ "  .u-row {\r\n"
				+ "    width: 600px !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row .u-col {\r\n"
				+ "    vertical-align: top;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-row .u-col-100 {\r\n"
				+ "    width: 600px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "@media (max-width: 620px) {\r\n"
				+ "  .u-row-container {\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    padding-left: 0px !important;\r\n"
				+ "    padding-right: 0px !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row .u-col {\r\n"
				+ "    min-width: 320px !important;\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    display: block !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row {\r\n"
				+ "    width: calc(100% - 40px) !important;\r\n"
				+ "  }\r\n"
				+ "  .u-col {\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "  .u-col > div {\r\n"
				+ "    margin: 0 auto;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "body {\r\n"
				+ "  margin: 0;\r\n"
				+ "  padding: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table,\r\n"
				+ "tr,\r\n"
				+ "td {\r\n"
				+ "  vertical-align: top;\r\n"
				+ "  border-collapse: collapse;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "p {\r\n"
				+ "  margin: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".ie-container table,\r\n"
				+ ".mso-container table {\r\n"
				+ "  table-layout: fixed;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "* {\r\n"
				+ "  line-height: inherit;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "a[x-apple-data-detectors='true'] {\r\n"
				+ "  color: inherit !important;\r\n"
				+ "  text-decoration: none !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table, td { color: #000000; } a { color: #0000ee; text-decoration: underline; } @media (max-width: 480px) { #u_content_image_1 .v-src-width { width: auto !important; } #u_content_image_1 .v-src-max-width { max-width: 40% !important; } #u_content_heading_1 .v-font-size { font-size: 38px !important; } #u_content_image_17 .v-src-width { width: auto !important; } #u_content_image_17 .v-src-max-width { max-width: 40% !important; } #u_content_heading_4 .v-font-size { font-size: 38px !important; } #u_content_text_5 .v-container-padding-padding { padding: 10px 30px 11px 10px !important; } }\r\n"
				+ "    </style>\r\n"
				+ "  \r\n"
				+ "  \r\n"
				+ "\r\n"
				+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #536068;color: #000000\">\r\n"
				+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
				+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
				+ "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #536068;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "  <tr style=\"vertical-align: top\">\r\n"
				+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
				+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #536068;\"><![endif]-->\r\n"
				+ "    \r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f1f2f6;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #f1f2f6;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"background-color: #f65050;width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"background-color: #f65050;width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table id=\"u_content_image_1\" style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px 31px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      \r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://firebasestorage.googleapis.com/v0/b/tshepo-9129c.appspot.com/o/uploads%2Fposts%2Flogo.jpg?alt=media&token=7e0700de-4628-4645-899a-2960dc65eea0\" alt=\"Logo\" title=\"Logo\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 16%;max-width: 92.8px;\" width=\"92.8\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      \r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #fbfcff;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #fbfcff;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table id=\"u_content_heading_1\" style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:50px 10px 30px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <h1 class=\"v-font-size\" style=\"margin: 0px; color: #ec3b3e; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Montserrat',sans-serif; font-size: 36px;\">\r\n"
				+ "    Welcome! "+name+"\r\n"
				+ "  </h1>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"82%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f65050;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table id=\"u_content_image_17\" style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px 31px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      \r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://firebasestorage.googleapis.com/v0/b/tshepo-9129c.appspot.com/o/f72d2cde-068d-487a-9bf3-e5248f89b238.png?alt=media&token=36492f3f-581a-4d93-bc83-3faee51530e9\" alt=\"Logo\" title=\"Logo\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 25%;max-width: 145px;\" width=\"145\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      \r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table id=\"u_content_heading_4\" style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:50px 10px 30px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <h3 class=\"v-font-size\" style=\"margin: 0px; color: #ec3b3e; line-height: 100%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Montserrat',sans-serif; font-size: 17px;\">\r\n"
				+ "    confirm your account, link expires in 30 minutes time.\r\n"
				+ "  </h3>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #ffffff;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"82%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f65050;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:15px 10px 30px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<div align=\"center\">\r\n"
				+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Montserrat',sans-serif;\"><tr><td style=\"font-family:'Montserrat',sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://unlayer.com\" style=\"height:49px; v-text-anchor:middle; width:215px;\" arcsize=\"0%\" stroke=\"f\" fillcolor=\"#f65050\"><w:anchorlock/><center style=\"color:#FFFFFF;font-family:'Montserrat',sans-serif;\"><![endif]-->\r\n"
				+ "    <a href=\""+link+" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:'Montserrat',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #f65050; border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\r\n"
				+ "      <span style=\"display:block;padding:16px 50px;line-height:120%;\"><strong><span style=\"font-size: 14px; line-height: 16.8px;\">CONFIRM HERE</span></strong></span>\r\n"
				+ "    </a>\r\n"
				+ "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"82%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f65050;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table id=\"u_content_text_5\" style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 30px 20px 40px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div style=\"color: #f65050; line-height: 190%; text-align: left; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 190%; text-align: center;\">Or Resend Link</p>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:15px 10px 30px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<div align=\"center\">\r\n"
				+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Montserrat',sans-serif;\"><tr><td style=\"font-family:'Montserrat',sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://unlayer.com\" style=\"height:49px; v-text-anchor:middle; width:190px;\" arcsize=\"0%\" stroke=\"f\" fillcolor=\"#f65050\"><w:anchorlock/><center style=\"color:#FFFFFF;font-family:'Montserrat',sans-serif;\"><![endif]-->\r\n"
				+ "    <a href=\"https://unlayer.com\" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:'Montserrat',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #f65050; border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\r\n"
				+ "      <span style=\"display:block;padding:16px 50px;line-height:120%;\"><strong><span style=\"font-size: 14px; line-height: 16.8px;\">Resend Link</span></strong></span>\r\n"
				+ "    </a>\r\n"
				+ "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #fbfcff;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #fbfcff;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"82%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f65050;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div style=\"color: #f65050; line-height: 190%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 190%;\">Want to change how you receive these emails?</p>\r\n"
				+ "<p style=\"font-size: 14px; line-height: 190%;\">You can update your preferences or unsubscribe from this list.</p>\r\n"
				+ "<p style=\"font-size: 14px; line-height: 190%;\">&nbsp;</p>\r\n"
				+ "<p style=\"font-size: 14px; line-height: 190%;\">&copy; 2022 Tshepo Mokoena. All Rights Reserved.</p>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      \r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://firebasestorage.googleapis.com/v0/b/tshepo-9129c.appspot.com/o/uploads%2Fweb%2Femail%2F1652784863534-KI1mOJYURjOhbzpd.png?alt=media&token=d042a19b-9e5b-4c53-9a87-96dd42c5fd31\" alt=\"border\" title=\"border\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 600px;\" width=\"600\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      \r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "  </table>\r\n"
				+ "  <!--[if mso]></div><![endif]-->\r\n"
				+ "  <!--[if IE]></div><![endif]-->\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>\r\n"
				+ "";
	}


	public static String accountConfirmed(String firstName) 
	{
		return "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
				+ "<head>\r\n"
				+ "<!--[if gte mso 9]>\r\n"
				+ "<xml>\r\n"
				+ "  <o:OfficeDocumentSettings>\r\n"
				+ "    <o:AllowPNG/>\r\n"
				+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
				+ "  </o:OfficeDocumentSettings>\r\n"
				+ "</xml>\r\n"
				+ "<![endif]-->\r\n"
				+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
				+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
				+ "  <title></title>\r\n"
				+ "  \r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "      @media only screen and (min-width: 620px) {\r\n"
				+ "  .u-row {\r\n"
				+ "    width: 600px !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row .u-col {\r\n"
				+ "    vertical-align: top;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-row .u-col-100 {\r\n"
				+ "    width: 600px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "@media (max-width: 620px) {\r\n"
				+ "  .u-row-container {\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    padding-left: 0px !important;\r\n"
				+ "    padding-right: 0px !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row .u-col {\r\n"
				+ "    min-width: 320px !important;\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    display: block !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row {\r\n"
				+ "    width: calc(100% - 40px) !important;\r\n"
				+ "  }\r\n"
				+ "  .u-col {\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "  .u-col > div {\r\n"
				+ "    margin: 0 auto;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "body {\r\n"
				+ "  margin: 0;\r\n"
				+ "  padding: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table,\r\n"
				+ "tr,\r\n"
				+ "td {\r\n"
				+ "  vertical-align: top;\r\n"
				+ "  border-collapse: collapse;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "p {\r\n"
				+ "  margin: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".ie-container table,\r\n"
				+ ".mso-container table {\r\n"
				+ "  table-layout: fixed;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "* {\r\n"
				+ "  line-height: inherit;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "a[x-apple-data-detectors='true'] {\r\n"
				+ "  color: inherit !important;\r\n"
				+ "  text-decoration: none !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table, td { color: #000000; } a { color: #0000ee; text-decoration: underline; } @media (max-width: 480px) { #u_content_image_1 .v-src-width { width: auto !important; } #u_content_image_1 .v-src-max-width { max-width: 40% !important; } #u_content_heading_1 .v-font-size { font-size: 38px !important; } #u_content_heading_4 .v-font-size { font-size: 38px !important; } #u_content_image_17 .v-src-width { width: auto !important; } #u_content_image_17 .v-src-max-width { max-width: 40% !important; } #u_content_text_5 .v-container-padding-padding { padding: 10px 30px 11px 10px !important; } }\r\n"
				+ "    </style>\r\n"
				+ "  \r\n"
				+ "  \r\n"
				+ "\r\n"
				+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #536068;color: #000000\">\r\n"
				+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
				+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
				+ "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #536068;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "  <tr style=\"vertical-align: top\">\r\n"
				+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
				+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #536068;\"><![endif]-->\r\n"
				+ "    \r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f1f2f6;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #f1f2f6;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"background-color: #f65050;width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"background-color: #f65050;width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table id=\"u_content_image_1\" style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px 31px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      \r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://firebasestorage.googleapis.com/v0/b/tshepo-9129c.appspot.com/o/uploads%2Fposts%2Flogo.jpg?alt=media&token=7e0700de-4628-4645-899a-2960dc65eea0\" alt=\"Logo\" title=\"Logo\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 16%;max-width: 92.8px;\" width=\"92.8\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      \r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #fbfcff;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #fbfcff;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table id=\"u_content_heading_1\" style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:50px 10px 30px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <h1 class=\"v-font-size\" style=\"margin: 0px; color: #ec3b3e; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Montserrat',sans-serif; font-size: 36px;\">\r\n"
				+ "    Thank You! "+firstName+"\r\n"
				+ "  </h1>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"82%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f65050;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table id=\"u_content_heading_4\" style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:50px 10px 30px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <h3 class=\"v-font-size\" style=\"margin: 0px; color: #ec3b3e; line-height: 100%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Montserrat',sans-serif; font-size: 18px;\">\r\n"
				+ "    your account is ready for use\r\n"
				+ "  </h3>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #ffffff;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"82%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f65050;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table id=\"u_content_image_17\" style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px 31px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      \r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://firebasestorage.googleapis.com/v0/b/tshepo-9129c.appspot.com/o/f72d2cde-068d-487a-9bf3-e5248f89b238.png?alt=media&token=36492f3f-581a-4d93-bc83-3faee51530e9\" alt=\"Logo\" title=\"Logo\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 16%;max-width: 92.8px;\" width=\"92.8\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      \r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:15px 10px 30px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<div align=\"center\">\r\n"
				+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Montserrat',sans-serif;\"><tr><td style=\"font-family:'Montserrat',sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://unlayer.com\" style=\"height:49px; v-text-anchor:middle; width:181px;\" arcsize=\"0%\" stroke=\"f\" fillcolor=\"#f65050\"><w:anchorlock/><center style=\"color:#FFFFFF;font-family:'Montserrat',sans-serif;\"><![endif]-->\r\n"
				+ "    <a href=\"https://unlayer.com\" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:'Montserrat',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #f65050; border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\r\n"
				+ "      <span style=\"display:block;padding:16px 50px;line-height:120%;\"><strong><span style=\"font-size: 14px; line-height: 16.8px;\">Edit Profile</span></strong></span>\r\n"
				+ "    </a>\r\n"
				+ "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"82%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f65050;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table id=\"u_content_text_5\" style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 30px 20px 40px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div style=\"color: #f65050; line-height: 190%; text-align: left; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 190%; text-align: center;\">Or Do Something else</p>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:15px 10px 30px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<div align=\"center\">\r\n"
				+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Montserrat',sans-serif;\"><tr><td style=\"font-family:'Montserrat',sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://unlayer.com\" style=\"height:49px; v-text-anchor:middle; width:185px;\" arcsize=\"0%\" stroke=\"f\" fillcolor=\"#f65050\"><w:anchorlock/><center style=\"color:#FFFFFF;font-family:'Montserrat',sans-serif;\"><![endif]-->\r\n"
				+ "    <a href=\"https://unlayer.com\" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:'Montserrat',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #f65050; border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\r\n"
				+ "      <span style=\"display:block;padding:16px 50px;line-height:120%;\"><strong><span style=\"font-size: 14px; line-height: 16.8px;\">Home Page</span></strong></span>\r\n"
				+ "    </a>\r\n"
				+ "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #fbfcff;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #fbfcff;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"82%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f65050;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div style=\"color: #f65050; line-height: 190%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 190%;\">Want to change how you receive these emails?</p>\r\n"
				+ "<p style=\"font-size: 14px; line-height: 190%;\">You can update your preferences or unsubscribe from this list.</p>\r\n"
				+ "<p style=\"font-size: 14px; line-height: 190%;\">&nbsp;</p>\r\n"
				+ "<p style=\"font-size: 14px; line-height: 190%;\">&copy; 2022 Tshepo Mokoena. All Rights Reserved.</p>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      \r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://firebasestorage.googleapis.com/v0/b/tshepo-9129c.appspot.com/o/uploads%2Fweb%2Femail%2F1652784863534-KI1mOJYURjOhbzpd.png?alt=media&token=d042a19b-9e5b-4c53-9a87-96dd42c5fd31\" alt=\"border\" title=\"border\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 600px;\" width=\"600\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      \r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "  </table>\r\n"
				+ "  <!--[if mso]></div><![endif]-->\r\n"
				+ "  <!--[if IE]></div><![endif]-->\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>\r\n"
				+ "";
	}
}
